### ISSUE TITLE
Support Chat doesn't exist 

### ISSUE THREAD

**Issue by thygrrr** [eurofurence/ef-app_android#145] opened 2017-08-16 19:58 UTC
When clicking on "Get help in the support Telegram", Telegram says "Sorry, this chat doesn't seem to exist"

**Comment by thygrrr** [comment] 2017-08-16 20:04
Affects Android app.

**Comment by lukashaertel** [comment] 2018-07-28 09:39
@thygrrr I can not reproduce this behavior. Can you validate if it's fixed or not?

**Comment by lukashaertel** [comment] 2018-07-30 07:06
I can't reproduce the bug. It seems that the URL at that point in time did point to a group chat that does not exist. The new chat, as configured in the remote preferences does exist. Closing this bug for now.

**Closed by lukashaertel** 2018-07-30 07:06 UTC
