### ISSUE TITLE
Fragments sometimes get a null context

### ISSUE THREAD

**Issue by lukashaertel** [eurofurence/ef-app_android#190] opened 2018-07-28 20:55 UTC
In some cases, i.e. after a having the app suspended for longer times, opening the app again causes the app to crash with a null pointer exception in fragment create view.
A possible solution might be in [this thread](https://stackoverflow.com/questions/47987649/why-getcontext-in-fragment-sometimes-returns-null).

**Comment by Pinselohrkater** [comment] 2018-07-31 06:33
Was presumably fixed in #195 - I was unable to reproduce it.

**Closed by Pinselohrkater** 2018-07-31 06:33 UTC
Labels: bug, in-review
